# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6f0897f91a534fa323bc738d06efc2270347d06e1f416fc8ac52b447f78b72bf24ce53ae7c2547539800e5ab9be57f80c363460de2180d6550f333ccc5911db

test:
  secret_key_base: cd8ef3f7edbf969c6379cd87e6ab0c4e4253d15a2315f9b4f51a1ff06cbf4a55c409654a1fd5f7632527a6301e650ccefdb6796c3e81d9b27b5e0c20e5253994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
